### ISSUE TITLE
Brainstorm tasks/jobs/activities necessary to fulfill our mission

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/core_mission#7]
... in order to make our vision real.

See [exec meeting 2019-10-29 notes](https://hackmd.io/fdRXEcqSQEGt7oOmMUy_Iw) for more background.

- [x] Make poll to find a suitable time (@yeea)

@resbazaz/steering-committee members to indicate availability:

- [x] Emily - @MagicMilly
- [x] Ailene - @yeea 
- [x] Drake - @drakeasberry 
- [x] Rebecca - @vanderpoolrr 
- [x] Alex B. - @alex-r-bigelow
- [x] Blake - @bjoyce3 
- [x] Julian - @julianpistorius 
- [x] Kelsey - @kelseygonzalez 
- [x] Jeff - @jcoliver 

Special member outside the steering committee:

- [x] Meghan - @megbalk

**Comment by julianpistorius** [comment]
@resbazaz/steering-committee Please mark your calendars for: Monday, 2019-11-25, 4pm

**Comment by alex-r-bigelow** [comment]
A test to see if the LucidChart plugin works:

https://www.lucidchart.com/invitations/accept/7bd80635-8517-468c-9693-0824ad5aa76f

**Comment by kelseygonzalez** [comment]
Looks fine to me!

**Comment by alex-r-bigelow** [comment]
(edited the link so that others can edit as well...)

**Comment by alex-r-bigelow** [comment]
Sorry for the delay (things like regular work distracted me); I made a quick-and-dirty [transcription of our sticky notes + an ugly chart](https://github.com/resbazaz/2019-11-25-brainstorming) because Lucid apparently doesn't let you edit beyond a certain number of shapes without buying the pro version.

All of us should be able to edit the chart from github; no local cloning should necessary—but you might need to go to Developer tools -> Network -> Disable cache to see your own recent changes.

(Also, apparently I don't have privileges to delete my `brainstorming-notes` branch on this repo—initially I tried to make the chart a subdirectory inside this one, but my original githack idea didn't work. If anyone with privileges sees it, feel free to trash it)

**Comment by julianpistorius** [comment]
Thank you very much @alex-r-bigelow! 🙇 

> (Also, apparently I don't have privileges to delete my `brainstorming-notes` branch on this repo—initially I tried to make the chart a subdirectory inside this one, but my original githack idea didn't work. If anyone with privileges sees it, feel free to trash it)

I trashed it.

**Comment by kelseygonzalez** [comment]
Thanks @alex-r-bigelow  - this is awesome!

**Comment by julianpistorius** [comment]
@kelseygonzalez @alex-r-bigelow @yeea What's next?

**Comment by alex-r-bigelow** [comment]
I think we wanted to create small overlapping teams, assigned to each of the categories?

There are nine members and eight first-tier categories (potential teams), although the communication category could probably be split into two teams. That would make the math easy: if we want teams of size _n_, everyone would be responsible to sign up for _n_ teams.

My vote would be for _n_ = 3.

**Comment by yeea** [comment]
I like Alex's overarching idea! I would augment it by adding that we'd talked about some teams probably needing more people/effort than others due to complexity, so we can sort of fudge into a fourth team if it suits us or we collectively think that team needs more members/another team could use less

**Comment by kelseygonzalez** [comment]
It really comes down to how many people we want on each "team". Basically, how many people need to be on the communication committee, the event committee, etc? Once we establish that I really like Alex's idea of spreading us around onto the different committees so that we have good coverage and then recruiting others to get more involved on these committees as well.

(You have no idea how many times I misspelled "committee" on this reponse!)
